//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.17 at 02:07:24 PM CET 
//


package model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link Consumers }
     * 
     */
    public Consumers createConsumers() {
        return new Consumers();
    }

    /**
     * Create an instance of {@link ConsumerT }
     * 
     */
    public ConsumerT createConsumerT() {
        return new ConsumerT();
    }

    /**
     * Create an instance of {@link Producers }
     * 
     */
    public Producers createProducers() {
        return new Producers();
    }

    /**
     * Create an instance of {@link ProducerT }
     * 
     */
    public ProducerT createProducerT() {
        return new ProducerT();
    }

    /**
     * Create an instance of {@link TimeT }
     * 
     */
    public TimeT createTimeT() {
        return new TimeT();
    }

    /**
     * Create an instance of {@link DatasizeT }
     * 
     */
    public DatasizeT createDatasizeT() {
        return new DatasizeT();
    }

    /**
     * Create an instance of {@link BehaviourT }
     * 
     */
    public BehaviourT createBehaviourT() {
        return new BehaviourT();
    }

}
